### PR TITLE
Add docs build and populate content

### PR DESCRIPTION
**Pull request by willGraham01**
## Description

**What is this PR**

- [ ] Bug fix
- [x] Addition of a new feature
- [ ] Other

**Why is this PR needed?**

Allows us to host more expansive documentation than just that in the README.

**What does this PR do?**

- Adds a docs build and publish workflow
- Adds scope to write fuller documentation for the plugin(s) that are developed here.

## How has this PR been tested?

Please explain how any new code has been tested, and how you have ensured that no existing functionality has changed.

## Checklist:

- [ ] The code has been tested locally
- [ ] Tests have been added to cover all new functionality (unit & integration)
- [ ] The documentation has been updated to reflect any changes
- [ ] The code has been formatted with [pre-commit](https://pre-commit.com/)

### CODE REVIEW

**Comment by K-Meech** [comment]
Do we want to update the installation instructions on the top `index.md`? Currently they refer to installing from pip, rather than from a locally cloned repo.

**Comment by K-Meech** [comment]
Also seems like sphinx doesn't understand emojis unfortunately (last line of the group_layers `index.md`)

**Comment by willGraham01** [comment]
> Do we want to update the installation instructions on the top index.md? Currently they refer to installing from pip, rather than from a locally cloned repo.

This is probably a question for @alessandrofelder as to whether he wants to release the plugin on `PyPI` and napari hub, or would prefer it stayed as a local installation thing. If we want to get people testing the plugin, I would guess an alpha-release would be best. CI should be setup to handle this (save for the first push to `PyPI`) - though we might want a slightly more informative name for the plugin :joy:

**Review by alessandrofelder — APPROVED** [review]
This is great - thanks a lot @K-Meech and @willGraham01

**Pull request merged**
